-- RLS: envolve auth.uid() em (select auth.uid()) para o Postgres avaliar uma vez por consulta,
-- nao por linha (advisor auth_rls_initplan). Recria as policies do schema public sem mudar a regra.
-- Gerado a partir do baseline; seguro rodar mais de uma vez. Aplicar pelo SQL Editor.

DROP POLICY IF EXISTS "as del" ON public.animal_sales;
CREATE POLICY "as del" ON public.animal_sales AS PERMISSIVE FOR DELETE TO authenticated USING ((has_permission((select auth.uid()), 'sales'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "as ins" ON public.animal_sales;
CREATE POLICY "as ins" ON public.animal_sales AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((has_permission((select auth.uid()), 'sales'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "as sel" ON public.animal_sales;
CREATE POLICY "as sel" ON public.animal_sales AS PERMISSIVE FOR SELECT TO authenticated USING ((has_permission((select auth.uid()), 'sales'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "as upd" ON public.animal_sales;
CREATE POLICY "as upd" ON public.animal_sales AS PERMISSIVE FOR UPDATE TO authenticated USING ((has_permission((select auth.uid()), 'sales'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "ala del" ON public.auction_lot_animals;
CREATE POLICY "ala del" ON public.auction_lot_animals AS PERMISSIVE FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "ala ins" ON public.auction_lot_animals;
CREATE POLICY "ala ins" ON public.auction_lot_animals AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "ala sel" ON public.auction_lot_animals;
CREATE POLICY "ala sel" ON public.auction_lot_animals AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "ala upd" ON public.auction_lot_animals;
CREATE POLICY "ala upd" ON public.auction_lot_animals AS PERMISSIVE FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "al del" ON public.auction_lots;
CREATE POLICY "al del" ON public.auction_lots AS PERMISSIVE FOR DELETE TO authenticated USING ((has_permission((select auth.uid()), 'sales'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "al ins" ON public.auction_lots;
CREATE POLICY "al ins" ON public.auction_lots AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((has_permission((select auth.uid()), 'sales'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "al sel" ON public.auction_lots;
CREATE POLICY "al sel" ON public.auction_lots AS PERMISSIVE FOR SELECT TO authenticated USING ((has_permission((select auth.uid()), 'sales'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "al upd" ON public.auction_lots;
CREATE POLICY "al upd" ON public.auction_lots AS PERMISSIVE FOR UPDATE TO authenticated USING ((has_permission((select auth.uid()), 'sales'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "audit select admin" ON public.audit_log;
CREATE POLICY "audit select admin" ON public.audit_log AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "audit_log insert authenticated" ON public.audit_log;
CREATE POLICY "audit_log insert authenticated" ON public.audit_log AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((select auth.uid()) IS NOT NULL));
DROP POLICY IF EXISTS bank_account_units_delete ON public.bank_account_units;
CREATE POLICY bank_account_units_delete ON public.bank_account_units AS PERMISSIVE FOR DELETE TO authenticated USING (has_permission((select auth.uid()), 'bank_accounts'::app_module, 'edit'::permission_action));
DROP POLICY IF EXISTS bank_account_units_insert ON public.bank_account_units;
CREATE POLICY bank_account_units_insert ON public.bank_account_units AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (has_permission((select auth.uid()), 'bank_accounts'::app_module, 'edit'::permission_action));
DROP POLICY IF EXISTS bank_account_units_select ON public.bank_account_units;
CREATE POLICY bank_account_units_select ON public.bank_account_units AS PERMISSIVE FOR SELECT TO authenticated USING (can_view_bank_account((select auth.uid()), bank_account_id));
DROP POLICY IF EXISTS bank_accounts_delete ON public.bank_accounts;
CREATE POLICY bank_accounts_delete ON public.bank_accounts AS PERMISSIVE FOR DELETE TO authenticated USING (has_permission((select auth.uid()), 'bank_accounts'::app_module, 'delete'::permission_action));
DROP POLICY IF EXISTS bank_accounts_insert ON public.bank_accounts;
CREATE POLICY bank_accounts_insert ON public.bank_accounts AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (has_permission((select auth.uid()), 'bank_accounts'::app_module, 'create'::permission_action));
DROP POLICY IF EXISTS bank_accounts_select ON public.bank_accounts;
CREATE POLICY bank_accounts_select ON public.bank_accounts AS PERMISSIVE FOR SELECT TO authenticated USING (can_view_bank_account((select auth.uid()), id));
DROP POLICY IF EXISTS bank_accounts_update ON public.bank_accounts;
CREATE POLICY bank_accounts_update ON public.bank_accounts AS PERMISSIVE FOR UPDATE TO authenticated USING (has_permission((select auth.uid()), 'bank_accounts'::app_module, 'edit'::permission_action)) WITH CHECK (has_permission((select auth.uid()), 'bank_accounts'::app_module, 'edit'::permission_action));
DROP POLICY IF EXISTS "bc delete" ON public.bank_contracts;
CREATE POLICY "bc delete" ON public.bank_contracts AS PERMISSIVE FOR DELETE TO authenticated USING ((has_permission((select auth.uid()), 'bank_contracts'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "bc insert" ON public.bank_contracts;
CREATE POLICY "bc insert" ON public.bank_contracts AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((has_permission((select auth.uid()), 'bank_contracts'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "bc select" ON public.bank_contracts;
CREATE POLICY "bc select" ON public.bank_contracts AS PERMISSIVE FOR SELECT TO authenticated USING ((has_permission((select auth.uid()), 'bank_contracts'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "bc update" ON public.bank_contracts;
CREATE POLICY "bc update" ON public.bank_contracts AS PERMISSIVE FOR UPDATE TO authenticated USING ((has_permission((select auth.uid()), 'bank_contracts'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((has_permission((select auth.uid()), 'bank_contracts'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "admin delete units" ON public.business_units;
CREATE POLICY "admin delete units" ON public.business_units AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "admin insert units" ON public.business_units;
CREATE POLICY "admin insert units" ON public.business_units AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "admin update units" ON public.business_units;
CREATE POLICY "admin update units" ON public.business_units AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "auth view units" ON public.business_units;
CREATE POLICY "auth view units" ON public.business_units AS PERMISSIVE FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "cat delete" ON public.categories;
CREATE POLICY "cat delete" ON public.categories AS PERMISSIVE FOR DELETE TO authenticated USING ((has_permission((select auth.uid()), 'categories'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "cat insert" ON public.categories;
CREATE POLICY "cat insert" ON public.categories AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((has_permission((select auth.uid()), 'categories'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "cat select" ON public.categories;
CREATE POLICY "cat select" ON public.categories AS PERMISSIVE FOR SELECT TO authenticated USING ((has_permission((select auth.uid()), 'categories'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "cat update" ON public.categories;
CREATE POLICY "cat update" ON public.categories AS PERMISSIVE FOR UPDATE TO authenticated USING ((has_permission((select auth.uid()), 'categories'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "cli delete" ON public.clients;
CREATE POLICY "cli delete" ON public.clients AS PERMISSIVE FOR DELETE TO authenticated USING ((has_permission((select auth.uid()), 'clients'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "cli insert" ON public.clients;
CREATE POLICY "cli insert" ON public.clients AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((has_permission((select auth.uid()), 'clients'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "cli select" ON public.clients;
CREATE POLICY "cli select" ON public.clients AS PERMISSIVE FOR SELECT TO authenticated USING ((has_permission((select auth.uid()), 'clients'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "cli update" ON public.clients;
CREATE POLICY "cli update" ON public.clients AS PERMISSIVE FOR UPDATE TO authenticated USING ((has_permission((select auth.uid()), 'clients'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS employees_delete ON public.employees;
CREATE POLICY employees_delete ON public.employees AS PERMISSIVE FOR DELETE TO authenticated USING ((has_permission((select auth.uid()), 'employees'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS employees_insert ON public.employees;
CREATE POLICY employees_insert ON public.employees AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((has_permission((select auth.uid()), 'employees'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS employees_select ON public.employees;
CREATE POLICY employees_select ON public.employees AS PERMISSIVE FOR SELECT TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS employees_update ON public.employees;
CREATE POLICY employees_update ON public.employees AS PERMISSIVE FOR UPDATE TO authenticated USING ((has_permission((select auth.uid()), 'employees'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "hac delete" ON public.haras_animal_categories;
CREATE POLICY "hac delete" ON public.haras_animal_categories AS PERMISSIVE FOR DELETE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hac insert" ON public.haras_animal_categories;
CREATE POLICY "hac insert" ON public.haras_animal_categories AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hac select" ON public.haras_animal_categories;
CREATE POLICY "hac select" ON public.haras_animal_categories AS PERMISSIVE FOR SELECT TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hac update" ON public.haras_animal_categories;
CREATE POLICY "hac update" ON public.haras_animal_categories AS PERMISSIVE FOR UPDATE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "ham delete" ON public.haras_animal_movements;
CREATE POLICY "ham delete" ON public.haras_animal_movements AS PERMISSIVE FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "ham insert" ON public.haras_animal_movements;
CREATE POLICY "ham insert" ON public.haras_animal_movements AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "ham select" ON public.haras_animal_movements;
CREATE POLICY "ham select" ON public.haras_animal_movements AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hap delete" ON public.haras_animal_partners;
CREATE POLICY "hap delete" ON public.haras_animal_partners AS PERMISSIVE FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hap insert" ON public.haras_animal_partners;
CREATE POLICY "hap insert" ON public.haras_animal_partners AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hap select" ON public.haras_animal_partners;
CREATE POLICY "hap select" ON public.haras_animal_partners AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hap update" ON public.haras_animal_partners;
CREATE POLICY "hap update" ON public.haras_animal_partners AS PERMISSIVE FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hats delete" ON public.haras_animal_transaction_shares;
CREATE POLICY "hats delete" ON public.haras_animal_transaction_shares AS PERMISSIVE FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hats insert" ON public.haras_animal_transaction_shares;
CREATE POLICY "hats insert" ON public.haras_animal_transaction_shares AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hats select" ON public.haras_animal_transaction_shares;
CREATE POLICY "hats select" ON public.haras_animal_transaction_shares AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hats update" ON public.haras_animal_transaction_shares;
CREATE POLICY "hats update" ON public.haras_animal_transaction_shares AS PERMISSIVE FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hat delete" ON public.haras_animal_transactions;
CREATE POLICY "hat delete" ON public.haras_animal_transactions AS PERMISSIVE FOR DELETE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hat insert" ON public.haras_animal_transactions;
CREATE POLICY "hat insert" ON public.haras_animal_transactions AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hat select" ON public.haras_animal_transactions;
CREATE POLICY "hat select" ON public.haras_animal_transactions AS PERMISSIVE FOR SELECT TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hat update" ON public.haras_animal_transactions;
CREATE POLICY "hat update" ON public.haras_animal_transactions AS PERMISSIVE FOR UPDATE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hwh delete" ON public.haras_animal_weight_history;
CREATE POLICY "hwh delete" ON public.haras_animal_weight_history AS PERMISSIVE FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hwh insert" ON public.haras_animal_weight_history;
CREATE POLICY "hwh insert" ON public.haras_animal_weight_history AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hwh select" ON public.haras_animal_weight_history;
CREATE POLICY "hwh select" ON public.haras_animal_weight_history AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "haras_animals delete" ON public.haras_animals;
CREATE POLICY "haras_animals delete" ON public.haras_animals AS PERMISSIVE FOR DELETE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "haras_animals insert" ON public.haras_animals;
CREATE POLICY "haras_animals insert" ON public.haras_animals AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "haras_animals select" ON public.haras_animals;
CREATE POLICY "haras_animals select" ON public.haras_animals AS PERMISSIVE FOR SELECT TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "haras_animals update" ON public.haras_animals;
CREATE POLICY "haras_animals update" ON public.haras_animals AS PERMISSIVE FOR UPDATE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS breeding_sessions_delete ON public.haras_breeding_sessions;
CREATE POLICY breeding_sessions_delete ON public.haras_breeding_sessions AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS breeding_sessions_insert ON public.haras_breeding_sessions;
CREATE POLICY breeding_sessions_insert ON public.haras_breeding_sessions AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS breeding_sessions_select ON public.haras_breeding_sessions;
CREATE POLICY breeding_sessions_select ON public.haras_breeding_sessions AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS breeding_sessions_update ON public.haras_breeding_sessions;
CREATE POLICY breeding_sessions_update ON public.haras_breeding_sessions AS PERMISSIVE FOR UPDATE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_clients delete" ON public.haras_clients;
CREATE POLICY "haras_clients delete" ON public.haras_clients AS PERMISSIVE FOR DELETE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "haras_clients insert" ON public.haras_clients;
CREATE POLICY "haras_clients insert" ON public.haras_clients AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "haras_clients select" ON public.haras_clients;
CREATE POLICY "haras_clients select" ON public.haras_clients AS PERMISSIVE FOR SELECT TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "haras_clients update" ON public.haras_clients;
CREATE POLICY "haras_clients update" ON public.haras_clients AS PERMISSIVE FOR UPDATE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS haras_embryo_transfers_delete ON public.haras_embryo_transfers;
CREATE POLICY haras_embryo_transfers_delete ON public.haras_embryo_transfers AS PERMISSIVE FOR DELETE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS haras_embryo_transfers_insert ON public.haras_embryo_transfers;
CREATE POLICY haras_embryo_transfers_insert ON public.haras_embryo_transfers AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS haras_embryo_transfers_select ON public.haras_embryo_transfers;
CREATE POLICY haras_embryo_transfers_select ON public.haras_embryo_transfers AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS haras_embryo_transfers_update ON public.haras_embryo_transfers;
CREATE POLICY haras_embryo_transfers_update ON public.haras_embryo_transfers AS PERMISSIVE FOR UPDATE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS haras_embryos_delete ON public.haras_embryos;
CREATE POLICY haras_embryos_delete ON public.haras_embryos AS PERMISSIVE FOR DELETE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS haras_embryos_insert ON public.haras_embryos;
CREATE POLICY haras_embryos_insert ON public.haras_embryos AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS haras_embryos_select ON public.haras_embryos;
CREATE POLICY haras_embryos_select ON public.haras_embryos AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS haras_embryos_update ON public.haras_embryos;
CREATE POLICY haras_embryos_update ON public.haras_embryos AS PERMISSIVE FOR UPDATE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "feature_flags admin delete" ON public.haras_feature_flags;
CREATE POLICY "feature_flags admin delete" ON public.haras_feature_flags AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "feature_flags admin insert" ON public.haras_feature_flags;
CREATE POLICY "feature_flags admin insert" ON public.haras_feature_flags AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "feature_flags admin update" ON public.haras_feature_flags;
CREATE POLICY "feature_flags admin update" ON public.haras_feature_flags AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "feature_flags select" ON public.haras_feature_flags;
CREATE POLICY "feature_flags select" ON public.haras_feature_flags AS PERMISSIVE FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS fiv_delete ON public.haras_fiv_batches;
CREATE POLICY fiv_delete ON public.haras_fiv_batches AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS fiv_insert ON public.haras_fiv_batches;
CREATE POLICY fiv_insert ON public.haras_fiv_batches AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS fiv_select ON public.haras_fiv_batches;
CREATE POLICY fiv_select ON public.haras_fiv_batches AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS fiv_update ON public.haras_fiv_batches;
CREATE POLICY fiv_update ON public.haras_fiv_batches AS PERMISSIVE FOR UPDATE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS follicle_exams_delete_admin ON public.haras_follicle_exams;
CREATE POLICY follicle_exams_delete_admin ON public.haras_follicle_exams AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS follicle_exams_insert ON public.haras_follicle_exams;
CREATE POLICY follicle_exams_insert ON public.haras_follicle_exams AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS follicle_exams_select ON public.haras_follicle_exams;
CREATE POLICY follicle_exams_select ON public.haras_follicle_exams AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS follicle_exams_update ON public.haras_follicle_exams;
CREATE POLICY follicle_exams_update ON public.haras_follicle_exams AS PERMISSIVE FOR UPDATE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS follicle_readings_delete_admin ON public.haras_follicle_readings;
CREATE POLICY follicle_readings_delete_admin ON public.haras_follicle_readings AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS follicle_readings_insert ON public.haras_follicle_readings;
CREATE POLICY follicle_readings_insert ON public.haras_follicle_readings AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS follicle_readings_select ON public.haras_follicle_readings;
CREATE POLICY follicle_readings_select ON public.haras_follicle_readings AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS follicle_readings_update ON public.haras_follicle_readings;
CREATE POLICY follicle_readings_update ON public.haras_follicle_readings AS PERMISSIVE FOR UPDATE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS opu_delete ON public.haras_opu_sessions;
CREATE POLICY opu_delete ON public.haras_opu_sessions AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS opu_insert ON public.haras_opu_sessions;
CREATE POLICY opu_insert ON public.haras_opu_sessions AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS opu_select ON public.haras_opu_sessions;
CREATE POLICY opu_select ON public.haras_opu_sessions AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS opu_update ON public.haras_opu_sessions;
CREATE POLICY opu_update ON public.haras_opu_sessions AS PERMISSIVE FOR UPDATE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "hpl delete" ON public.haras_partner_locations;
CREATE POLICY "hpl delete" ON public.haras_partner_locations AS PERMISSIVE FOR DELETE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hpl insert" ON public.haras_partner_locations;
CREATE POLICY "hpl insert" ON public.haras_partner_locations AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hpl select" ON public.haras_partner_locations;
CREATE POLICY "hpl select" ON public.haras_partner_locations AS PERMISSIVE FOR SELECT TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hpl update" ON public.haras_partner_locations;
CREATE POLICY "hpl update" ON public.haras_partner_locations AS PERMISSIVE FOR UPDATE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS pregnancies_delete ON public.haras_pregnancies;
CREATE POLICY pregnancies_delete ON public.haras_pregnancies AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS pregnancies_insert ON public.haras_pregnancies;
CREATE POLICY pregnancies_insert ON public.haras_pregnancies AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS pregnancies_select ON public.haras_pregnancies;
CREATE POLICY pregnancies_select ON public.haras_pregnancies AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS pregnancies_update ON public.haras_pregnancies;
CREATE POLICY pregnancies_update ON public.haras_pregnancies AS PERMISSIVE FOR UPDATE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS diagnostics_delete ON public.haras_pregnancy_diagnostics;
CREATE POLICY diagnostics_delete ON public.haras_pregnancy_diagnostics AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS diagnostics_insert ON public.haras_pregnancy_diagnostics;
CREATE POLICY diagnostics_insert ON public.haras_pregnancy_diagnostics AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS diagnostics_select ON public.haras_pregnancy_diagnostics;
CREATE POLICY diagnostics_select ON public.haras_pregnancy_diagnostics AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS diagnostics_update ON public.haras_pregnancy_diagnostics;
CREATE POLICY diagnostics_update ON public.haras_pregnancy_diagnostics AS PERMISSIVE FOR UPDATE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchase_commission_installments delete" ON public.haras_purchase_commission_installments;
CREATE POLICY "haras_purchase_commission_installments delete" ON public.haras_purchase_commission_installments AS PERMISSIVE FOR DELETE TO public USING ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchase_commission_installments insert" ON public.haras_purchase_commission_installments;
CREATE POLICY "haras_purchase_commission_installments insert" ON public.haras_purchase_commission_installments AS PERMISSIVE FOR INSERT TO public WITH CHECK ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchase_commission_installments select" ON public.haras_purchase_commission_installments;
CREATE POLICY "haras_purchase_commission_installments select" ON public.haras_purchase_commission_installments AS PERMISSIVE FOR SELECT TO public USING ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchase_commission_installments update" ON public.haras_purchase_commission_installments;
CREATE POLICY "haras_purchase_commission_installments update" ON public.haras_purchase_commission_installments AS PERMISSIVE FOR UPDATE TO public USING ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchase_commissions delete" ON public.haras_purchase_commissions;
CREATE POLICY "haras_purchase_commissions delete" ON public.haras_purchase_commissions AS PERMISSIVE FOR DELETE TO public USING ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchase_commissions insert" ON public.haras_purchase_commissions;
CREATE POLICY "haras_purchase_commissions insert" ON public.haras_purchase_commissions AS PERMISSIVE FOR INSERT TO public WITH CHECK ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchase_commissions select" ON public.haras_purchase_commissions;
CREATE POLICY "haras_purchase_commissions select" ON public.haras_purchase_commissions AS PERMISSIVE FOR SELECT TO public USING ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchase_commissions update" ON public.haras_purchase_commissions;
CREATE POLICY "haras_purchase_commissions update" ON public.haras_purchase_commissions AS PERMISSIVE FOR UPDATE TO public USING ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchase_installments delete" ON public.haras_purchase_installments;
CREATE POLICY "haras_purchase_installments delete" ON public.haras_purchase_installments AS PERMISSIVE FOR DELETE TO public USING ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchase_installments insert" ON public.haras_purchase_installments;
CREATE POLICY "haras_purchase_installments insert" ON public.haras_purchase_installments AS PERMISSIVE FOR INSERT TO public WITH CHECK ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchase_installments select" ON public.haras_purchase_installments;
CREATE POLICY "haras_purchase_installments select" ON public.haras_purchase_installments AS PERMISSIVE FOR SELECT TO public USING ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchase_installments update" ON public.haras_purchase_installments;
CREATE POLICY "haras_purchase_installments update" ON public.haras_purchase_installments AS PERMISSIVE FOR UPDATE TO public USING ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchases delete" ON public.haras_purchases;
CREATE POLICY "haras_purchases delete" ON public.haras_purchases AS PERMISSIVE FOR DELETE TO public USING ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchases insert" ON public.haras_purchases;
CREATE POLICY "haras_purchases insert" ON public.haras_purchases AS PERMISSIVE FOR INSERT TO public WITH CHECK ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchases select" ON public.haras_purchases;
CREATE POLICY "haras_purchases select" ON public.haras_purchases AS PERMISSIVE FOR SELECT TO public USING ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "haras_purchases update" ON public.haras_purchases;
CREATE POLICY "haras_purchases update" ON public.haras_purchases AS PERMISSIVE FOR UPDATE TO public USING ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((has_permission((select auth.uid()), 'haras_purchases'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "hrii delete" ON public.haras_recurring_invoice_items;
CREATE POLICY "hrii delete" ON public.haras_recurring_invoice_items AS PERMISSIVE FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hrii insert" ON public.haras_recurring_invoice_items;
CREATE POLICY "hrii insert" ON public.haras_recurring_invoice_items AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hrii select" ON public.haras_recurring_invoice_items;
CREATE POLICY "hrii select" ON public.haras_recurring_invoice_items AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hrii update" ON public.haras_recurring_invoice_items;
CREATE POLICY "hrii update" ON public.haras_recurring_invoice_items AS PERMISSIVE FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "hri delete" ON public.haras_recurring_invoices;
CREATE POLICY "hri delete" ON public.haras_recurring_invoices AS PERMISSIVE FOR DELETE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hri insert" ON public.haras_recurring_invoices;
CREATE POLICY "hri insert" ON public.haras_recurring_invoices AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hri select" ON public.haras_recurring_invoices;
CREATE POLICY "hri select" ON public.haras_recurring_invoices AS PERMISSIVE FOR SELECT TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hri update" ON public.haras_recurring_invoices;
CREATE POLICY "hri update" ON public.haras_recurring_invoices AS PERMISSIVE FOR UPDATE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hrr select" ON public.haras_recurring_runs;
CREATE POLICY "hrr select" ON public.haras_recurring_runs AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "repro_settings delete" ON public.haras_reproduction_settings;
CREATE POLICY "repro_settings delete" ON public.haras_reproduction_settings AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "repro_settings insert" ON public.haras_reproduction_settings;
CREATE POLICY "repro_settings insert" ON public.haras_reproduction_settings AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "repro_settings select" ON public.haras_reproduction_settings;
CREATE POLICY "repro_settings select" ON public.haras_reproduction_settings AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "repro_settings update" ON public.haras_reproduction_settings;
CREATE POLICY "repro_settings update" ON public.haras_reproduction_settings AS PERMISSIVE FOR UPDATE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS semen_batches_delete ON public.haras_semen_batches;
CREATE POLICY semen_batches_delete ON public.haras_semen_batches AS PERMISSIVE FOR DELETE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS semen_batches_insert ON public.haras_semen_batches;
CREATE POLICY semen_batches_insert ON public.haras_semen_batches AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS semen_batches_select ON public.haras_semen_batches;
CREATE POLICY semen_batches_select ON public.haras_semen_batches AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS semen_batches_update ON public.haras_semen_batches;
CREATE POLICY semen_batches_update ON public.haras_semen_batches AS PERMISSIVE FOR UPDATE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS semen_collections_delete ON public.haras_semen_collections;
CREATE POLICY semen_collections_delete ON public.haras_semen_collections AS PERMISSIVE FOR DELETE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS semen_collections_insert ON public.haras_semen_collections;
CREATE POLICY semen_collections_insert ON public.haras_semen_collections AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS semen_collections_select ON public.haras_semen_collections;
CREATE POLICY semen_collections_select ON public.haras_semen_collections AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS semen_collections_update ON public.haras_semen_collections;
CREATE POLICY semen_collections_update ON public.haras_semen_collections AS PERMISSIVE FOR UPDATE TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id))) WITH CHECK ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS semen_movements_admin_delete ON public.haras_semen_movements;
CREATE POLICY semen_movements_admin_delete ON public.haras_semen_movements AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS semen_movements_admin_insert ON public.haras_semen_movements;
CREATE POLICY semen_movements_admin_insert ON public.haras_semen_movements AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin((select auth.uid())));
DROP POLICY IF EXISTS semen_movements_admin_update ON public.haras_semen_movements;
CREATE POLICY semen_movements_admin_update ON public.haras_semen_movements AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin((select auth.uid()))) WITH CHECK (is_admin((select auth.uid())));
DROP POLICY IF EXISTS semen_movements_select ON public.haras_semen_movements;
CREATE POLICY semen_movements_select ON public.haras_semen_movements AS PERMISSIVE FOR SELECT TO authenticated USING ((is_admin((select auth.uid())) OR can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "hs delete" ON public.haras_services;
CREATE POLICY "hs delete" ON public.haras_services AS PERMISSIVE FOR DELETE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hs insert" ON public.haras_services;
CREATE POLICY "hs insert" ON public.haras_services AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hs select" ON public.haras_services;
CREATE POLICY "hs select" ON public.haras_services AS PERMISSIVE FOR SELECT TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "hs update" ON public.haras_services;
CREATE POLICY "hs update" ON public.haras_services AS PERMISSIVE FOR UPDATE TO authenticated USING (can_access_unit((select auth.uid()), business_unit_id));
DROP POLICY IF EXISTS "shadow_log admin select" ON public.haras_shadow_log;
CREATE POLICY "shadow_log admin select" ON public.haras_shadow_log AS PERMISSIVE FOR SELECT TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "inst delete" ON public.loan_installments;
CREATE POLICY "inst delete" ON public.loan_installments AS PERMISSIVE FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "inst insert" ON public.loan_installments;
CREATE POLICY "inst insert" ON public.loan_installments AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "inst select" ON public.loan_installments;
CREATE POLICY "inst select" ON public.loan_installments AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "inst update" ON public.loan_installments;
CREATE POLICY "inst update" ON public.loan_installments AS PERMISSIVE FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "loan delete" ON public.loans;
CREATE POLICY "loan delete" ON public.loans AS PERMISSIVE FOR DELETE TO authenticated USING ((has_permission((select auth.uid()), 'loans'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "loan insert" ON public.loans;
CREATE POLICY "loan insert" ON public.loans AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((has_permission((select auth.uid()), 'loans'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "loan select" ON public.loans;
CREATE POLICY "loan select" ON public.loans AS PERMISSIVE FOR SELECT TO authenticated USING ((has_permission((select auth.uid()), 'loans'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "loan update" ON public.loans;
CREATE POLICY "loan update" ON public.loans AS PERMISSIVE FOR UPDATE TO authenticated USING ((has_permission((select auth.uid()), 'loans'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS own_delete ON public.notifications;
CREATE POLICY own_delete ON public.notifications AS PERMISSIVE FOR DELETE TO public USING ((user_id = (select auth.uid())));
DROP POLICY IF EXISTS own_read ON public.notifications;
CREATE POLICY own_read ON public.notifications AS PERMISSIVE FOR SELECT TO public USING ((user_id = (select auth.uid())));
DROP POLICY IF EXISTS own_update ON public.notifications;
CREATE POLICY own_update ON public.notifications AS PERMISSIVE FOR UPDATE TO public USING ((user_id = (select auth.uid())));
DROP POLICY IF EXISTS "pay delete" ON public.payables;
CREATE POLICY "pay delete" ON public.payables AS PERMISSIVE FOR DELETE TO authenticated USING ((has_permission((select auth.uid()), 'payables'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "pay insert" ON public.payables;
CREATE POLICY "pay insert" ON public.payables AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((has_permission((select auth.uid()), 'payables'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "pay select" ON public.payables;
CREATE POLICY "pay select" ON public.payables AS PERMISSIVE FOR SELECT TO authenticated USING ((has_permission((select auth.uid()), 'payables'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "pay update" ON public.payables;
CREATE POLICY "pay update" ON public.payables AS PERMISSIVE FOR UPDATE TO authenticated USING ((has_permission((select auth.uid()), 'payables'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "admin delete profiles" ON public.profiles;
CREATE POLICY "admin delete profiles" ON public.profiles AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "users update own profile" ON public.profiles;
CREATE POLICY "users update own profile" ON public.profiles AS PERMISSIVE FOR UPDATE TO authenticated USING ((((select auth.uid()) = id) OR is_admin((select auth.uid()))));
DROP POLICY IF EXISTS "users view own profile" ON public.profiles;
CREATE POLICY "users view own profile" ON public.profiles AS PERMISSIVE FOR SELECT TO authenticated USING ((((select auth.uid()) = id) OR is_admin((select auth.uid()))));
DROP POLICY IF EXISTS "rec delete" ON public.receivables;
CREATE POLICY "rec delete" ON public.receivables AS PERMISSIVE FOR DELETE TO authenticated USING ((has_permission((select auth.uid()), 'receivables'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "rec insert" ON public.receivables;
CREATE POLICY "rec insert" ON public.receivables AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((has_permission((select auth.uid()), 'receivables'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "rec select" ON public.receivables;
CREATE POLICY "rec select" ON public.receivables AS PERMISSIVE FOR SELECT TO authenticated USING ((has_permission((select auth.uid()), 'receivables'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "rec update" ON public.receivables;
CREATE POLICY "rec update" ON public.receivables AS PERMISSIVE FOR UPDATE TO authenticated USING ((has_permission((select auth.uid()), 'receivables'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "rp delete" ON public.recurring_payables;
CREATE POLICY "rp delete" ON public.recurring_payables AS PERMISSIVE FOR DELETE TO authenticated USING ((has_permission((select auth.uid()), 'payables'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "rp insert" ON public.recurring_payables;
CREATE POLICY "rp insert" ON public.recurring_payables AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((has_permission((select auth.uid()), 'payables'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "rp select" ON public.recurring_payables;
CREATE POLICY "rp select" ON public.recurring_payables AS PERMISSIVE FOR SELECT TO authenticated USING ((has_permission((select auth.uid()), 'payables'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "rp update" ON public.recurring_payables;
CREATE POLICY "rp update" ON public.recurring_payables AS PERMISSIVE FOR UPDATE TO authenticated USING ((has_permission((select auth.uid()), 'payables'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "res delete" ON public.reservations;
CREATE POLICY "res delete" ON public.reservations AS PERMISSIVE FOR DELETE TO authenticated USING ((has_permission((select auth.uid()), 'reservations'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "res insert" ON public.reservations;
CREATE POLICY "res insert" ON public.reservations AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((has_permission((select auth.uid()), 'reservations'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "res select" ON public.reservations;
CREATE POLICY "res select" ON public.reservations AS PERMISSIVE FOR SELECT TO authenticated USING ((has_permission((select auth.uid()), 'reservations'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "res update" ON public.reservations;
CREATE POLICY "res update" ON public.reservations AS PERMISSIVE FOR UPDATE TO authenticated USING ((has_permission((select auth.uid()), 'reservations'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "read own bu sale installment notifications" ON public.sale_installment_notifications;
CREATE POLICY "read own bu sale installment notifications" ON public.sale_installment_notifications AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "si del" ON public.sale_installments;
CREATE POLICY "si del" ON public.sale_installments AS PERMISSIVE FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "si ins" ON public.sale_installments;
CREATE POLICY "si ins" ON public.sale_installments AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "si sel" ON public.sale_installments;
CREATE POLICY "si sel" ON public.sale_installments AS PERMISSIVE FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "si upd" ON public.sale_installments;
CREATE POLICY "si upd" ON public.sale_installments AS PERMISSIVE FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1
DROP POLICY IF EXISTS "tx delete" ON public.transactions;
CREATE POLICY "tx delete" ON public.transactions AS PERMISSIVE FOR DELETE TO authenticated USING ((has_permission((select auth.uid()), 'cash_flow'::app_module, 'delete'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "tx insert" ON public.transactions;
CREATE POLICY "tx insert" ON public.transactions AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((has_permission((select auth.uid()), 'cash_flow'::app_module, 'create'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "tx select" ON public.transactions;
CREATE POLICY "tx select" ON public.transactions AS PERMISSIVE FOR SELECT TO authenticated USING ((has_permission((select auth.uid()), 'cash_flow'::app_module, 'view'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "tx update" ON public.transactions;
CREATE POLICY "tx update" ON public.transactions AS PERMISSIVE FOR UPDATE TO authenticated USING ((has_permission((select auth.uid()), 'cash_flow'::app_module, 'edit'::permission_action) AND can_access_unit((select auth.uid()), business_unit_id)));
DROP POLICY IF EXISTS "admin manage perms delete" ON public.user_module_permissions;
CREATE POLICY "admin manage perms delete" ON public.user_module_permissions AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "admin manage perms insert" ON public.user_module_permissions;
CREATE POLICY "admin manage perms insert" ON public.user_module_permissions AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "admin manage perms update" ON public.user_module_permissions;
CREATE POLICY "admin manage perms update" ON public.user_module_permissions AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "view own permissions" ON public.user_module_permissions;
CREATE POLICY "view own permissions" ON public.user_module_permissions AS PERMISSIVE FOR SELECT TO authenticated USING (((user_id = (select auth.uid())) OR is_admin((select auth.uid()))));
DROP POLICY IF EXISTS "admin manage roles delete" ON public.user_roles;
CREATE POLICY "admin manage roles delete" ON public.user_roles AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "admin manage roles insert" ON public.user_roles;
CREATE POLICY "admin manage roles insert" ON public.user_roles AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "admin manage roles update" ON public.user_roles;
CREATE POLICY "admin manage roles update" ON public.user_roles AS PERMISSIVE FOR UPDATE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "view own role" ON public.user_roles;
CREATE POLICY "view own role" ON public.user_roles AS PERMISSIVE FOR SELECT TO authenticated USING (((user_id = (select auth.uid())) OR is_admin((select auth.uid()))));
DROP POLICY IF EXISTS "admin manage unit access delete" ON public.user_unit_access;
CREATE POLICY "admin manage unit access delete" ON public.user_unit_access AS PERMISSIVE FOR DELETE TO authenticated USING (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "admin manage unit access insert" ON public.user_unit_access;
CREATE POLICY "admin manage unit access insert" ON public.user_unit_access AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (is_admin((select auth.uid())));
DROP POLICY IF EXISTS "view own unit access" ON public.user_unit_access;
CREATE POLICY "view own unit access" ON public.user_unit_access AS PERMISSIVE FOR SELECT TO authenticated USING (((user_id = (select auth.uid())) OR is_admin((select auth.uid()))));
